### ISSUE TITLE
Specific operation to the minor objects

### ISSUE THREAD

**Issue by 1179021477** [naver-ai/cmo#2]
Figure.1 shows that two images are combined without any edges. It seems the objects inside are segmented not cropped.  What operation do you do to the minor object before combining？

**Comment by pseulki** [comment]
Hi, thank you for your interest.

Figure 1 is the concept picture to show the intuition of our idea.
As shown in Figure 2, images are randomly cropped to generate new images.
It is because random cropping is much more efficient for training, considering a very large amount of data today.

If you have any further question, please feel free to ask us :)

**Comment by 1179021477** [comment]
Thank you. Another question is the Minor-class-weighted Distribution. 
1. Is this strategy only applied to minor classes? 
2. what is the strategy of selecting the minor classes and major classes? 
3. The minor classes is pasted to all major classes?

**Comment by pseulki** [comment]
Hi, 
All your questions can be answered as following:
Minor-class-weighted distribution is not applied to minor classes only.
This strategy is to induce more minor classes for the foreground patch; and use the original distribution for the background so that we can leverage the rich context from major classes.
Since data are sampled from probability distribution, some foreground patches can be drawn from major classes, and vice versa.
That means, some major classes can be pasted to the minor classes too.
Please refer to our paper and codes for more details. :)
